import QRCode from 'qrcode.react'

import useConfirmation from '../../../hooks/useConfirmation'
import { QR_CODE_ICON, WHITE_ARROW } from '../../../../../../theme/sources'
import { I2FA } from '../../interfaces'

const TotpInfo = ({ dopFunc }: I2FA) => {
  const { authLinks } = useConfirmation()

  return (
    <>
      <div className="info-title">
        <img
          src={WHITE_ARROW}
          alt=""
          onClick={dopFunc ? () => dopFunc() : () => {}}
        />
        <div>Google Authenticator</div>
      </div>
      <div className="info-text">
        Protect your account by requiring an additional layer of security with
        2FA
      </div>
      <div className="info-instrac-block">
        <div className="number">1</div>
        <div className="instrac-text">
          Download and install an app Google Authenticator on your mobile device
        </div>
      </div>
      <div className="info-instrac-block">
        <div className="number">2</div>
        <div className="instrac-text">
          Open app and scan the QR code (or enter the code manually)
        </div>
      </div>
      <div className="info-instrac-block">
        <div className="number">3</div>
        <div className="instrac-text">
          Enter and verify the authenticatoin code generated by the app
        </div>
      </div>
      <div className="auth-links">
        {authLinks.map((el) => (
          <div className="auth-links-block">
            <a
              target="_blank" href={el.href}
              rel="noreferrer">
              <img src={el.icon} alt="" />
              <div>
                <div className="up-text">{el.description}</div>
                <div className="down-text">{el.name}</div>
              </div>
            </a>
            <div className="auth-qrcode">
              <img src={QR_CODE_ICON} alt="" />
              <div className="auth-tooltip">
                <div>
                  <QRCode
                    value={el.href} renderAs="canvas"
                    size={100} />
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </>
  )
}

export default TotpInfo
